### ISSUE TITLE
Question about the name of the repo....

### ISSUE THREAD

**Issue by puyihua** [meownoid/tensorflow-rbm#9]
Hi, your code is great and help me a lot when I use GBRMB to pretrain CNN. Thanks!
But I don't know why the name of this repo is "tensorfow-rbm" instead of "tensorf **l** ow-rbm"?
Maybe it will bring inconvenience when people try to find this repo using keyword " tensorflow "

**Comment by meownoid** [comment]
Thanks a lot! I can't believe I didn't notice it for four years!!!
